name: base
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pyyaml
  - cupy
  - opencv
  - pkg-config
  - libjpeg-turbo
  - opencv
  - numba
  - pip:
    - torch
    - torchvision